### ISSUE TITLE
The WinRM client cannot process the request

### ISSUE THREAD

**Issue by hktalent** [bohops/WSMan-WinRM#1]
cscript.exe test.js 192.168.xxxx whoami

Session: The WinRM client cannot process the request. If the authentication scheme is different from Kerberos, or if the client computer is not joined to a domain, then HTTPS transport must be used or the destination machine must be added to the TrustedHosts configuration setting. Use winrm.cmd to configure TrustedHosts. Note that computers in the TrustedHosts list might not be authenticated. You can get more information about that by running the following command: winrm help config.

**Comment by bohops** [comment]
First, try running the command with the name of the host or FQDN of the host.  If that doesnt work, the problem is likely a WinRM issue.  The target machine must have WinRM enabled and configured for client requests, and the user account must have the proper rights to connect to the host to execute commands.  In short, if you can run a remote PowerShell command (e.g. Invoke-Command -ScriptBlock {whoami}} -ComputerName somehostname), then the scripts should work.
